import type { AppShellData, VideosData } from '@/lib/demo-client/types'

export const testAppShellData: AppShellData = {
  app: {
    name: 'Studio Pulse demo',
    demoMode: true,
    dataAsOf: '2026-04-01',
    version: 'test',
  },
  channel: {
    id: 'test-channel',
    name: 'Northstar Studio',
    subtitle: 'Synthetic analytics workspace',
    description: 'A public demo workspace.',
  },
  features: {
    overview: true,
    videos: true,
    growth: true,
    technicalAnalysis: true,
    metadata: true,
    breakout: true,
    creative: true,
    insights: true,
    songs: false,
  },
}

export const testVideosData: VideosData = {
  summary: {
    totalVideos: 3,
    topFormat: 'Explainer',
    strongestTheme: 'Prayer',
    medianCtr: 5.2,
  },
  items: [
    {
      id: 'video-1',
      title: 'Morning Prayer for Peace',
      publishedAt: '2026-03-12',
      views: 12000,
      watchHours: 840,
      impressions: 180000,
      ctr: 6.4,
      avdSeconds: 245,
      avp: 41.2,
      format: 'Explainer',
      theme: 'Prayer',
      score: 88,
      tier: 'Excellent',
      isLive: false,
      thumbnailLabel: 'Peace',
      summary: 'Strong evergreen signal',
    },
    {
      id: 'video-2',
      title: 'Live Psalm Study',
      publishedAt: '2026-03-19',
      views: 6400,
      watchHours: 520,
      impressions: 90000,
      ctr: 4.8,
      avdSeconds: 312,
      avp: 36.5,
      format: 'Live Study',
      theme: 'Psalms',
      score: 72,
      tier: 'Good',
      isLive: true,
      thumbnailLabel: 'Study',
      summary: 'Stable live replay performance',
    },
    {
      id: 'video-3',
      title: 'Bible Sleep Story',
      publishedAt: '2026-02-27',
      views: 8900,
      watchHours: 600,
      impressions: 150000,
      ctr: 5.1,
      avdSeconds: 278,
      avp: 39.8,
      format: 'Sleep Story',
      theme: 'Sleep',
      score: 79,
      tier: 'Good',
      isLive: false,
      thumbnailLabel: 'Sleep',
      summary: 'Consistent background listening audience',
    },
  ],
}
